# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install conan
        uses: turtlebrowser/get-conan@v1.0
      
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      # Runs conan install to fetch dependencies
      - name: Fetch dependencies
        working-directory: ${{github.workspace}}/build
        shell: bash
          # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: conan install .. -o build_tests:True
    
    # Build
      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
          # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: conan build ..
