name: Release

on:
  push:
    tags:
      - vt0.*

  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - compiler: gcc
            cc: gcc-9
            cxx: g++-9
            packages: gcc-9 g++-9
            conan_args:
            artifact: logpp-linux-gcc-static
          - compiler: clang
            cc: clang-10
            cxx: clang++-10
            packages: clang-10
            conan_args:
            artifact: logpp-linux-clang-static

    runs-on: ubuntu-latest
    name: build-${{ matrix.artifact }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        shell: bash
        run: |
            echo "RELEASE_TARGET_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            echo "LOGPP_VERSION=`bash tools/version.sh`" >> $GITHUB_ENV

      - name: Install compiler
        run: sudo apt install ${{ matrix.packages }}

      - name: Install conan
        uses: turtlebrowser/get-conan@v1.0

      - name: Create conan profile
        run: |
           conan profile new ${{ matrix.artifact }} --detect
           conan profile update settings.compiler.libcxx=libstdc++11 ${{ matrix.artifact }}
           conan profile update env.CXX=${{ matrix.cxx }} ${{ matrix.artifact }}
        env:
          CC:  ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build-${{ matrix.artifact }}

      - name: Fetch dependencies
        working-directory: ${{ github.workspace }}/build-${{ matrix.artifact }}
        shell: bash
        run: conan install .. -o build_tests=True ${{ matrix.conan_args }} -pr=${{ matrix.artifact }} --build=missing

      - name: Run CMake
        working-directory: ${{ github.workspace }}/build-${{ matrix.artifact }}
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_arguments }} ..

        # - name: Check version
        #   working-directory: ${{ github.workspace }}/build-${{ matrix.artifact }}
        #   shell: bash
        #   run: ${{github.workspace}}/tools/check-version.sh ${{ env.RELEASE_TARGET_VERSION }} vt

      - name: Build
        working-directory: ${{ github.workspace }}/build-${{ matrix.artifact }}
        shell: bash
        run: conan build ..

      - name: Package
        working-directory: ${{ github.workspace }}/build-${{ matrix.artifact }}
        shell: bash
        run: cpack
