name: Release

on:
  push:
    tags:
      - vt0.*

  workflow_dispatch:

jobs:
  build-linux-shared-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: echo "RELEASE_VER=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Check version
        run: ${{github.workspace}}/tools/check-version.sh ${{ env.RELEASE_VER }} vt
        working-directory: ${{github.workspace}}/build
