name: Release

on:
  push:
    tags:
      - vt0.*

  workflow_dispatch:

jobs:
  build-linux-shared-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: echo "RELEASE_VER=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Check version matching
        run: echo ${{ env.RELEASE_VER }}
